package com.idsoftware.orders.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Arrays;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class ProductOrder {
    private Integer orderId;
    private Integer productId;

    public static List<ProductOrder> productOrderList(){
        return Arrays.asList(
            new ProductOrder (1, 19),
            new ProductOrder (1, 21),
            new ProductOrder (1, 5),
            new ProductOrder (2, 17),
            new ProductOrder (2, 11),
            new ProductOrder (2, 14),
            new ProductOrder (2, 13),
            new ProductOrder (3, 5),
            new ProductOrder (3, 3),
            new ProductOrder (3, 19),
            new ProductOrder (3, 13),
            new ProductOrder (3, 15),
            new ProductOrder (4, 22),
            new ProductOrder (4, 26),
            new ProductOrder (4, 12),
            new ProductOrder (5, 5),
            new ProductOrder (6, 5),
            new ProductOrder (6, 12),
            new ProductOrder (7, 8),
            new ProductOrder (7, 25),
            new ProductOrder (7, 21),
            new ProductOrder (7, 1),
            new ProductOrder (7, 13),
            new ProductOrder (7, 10),
            new ProductOrder (8, 12),
            new ProductOrder (8, 8),
            new ProductOrder (9, 8),
            new ProductOrder (10, 14),
            new ProductOrder (10, 8),
            new ProductOrder (11, 12),
            new ProductOrder (11, 6),
            new ProductOrder (11, 21),
            new ProductOrder (11, 22),
            new ProductOrder (11, 27),
            new ProductOrder (11, 11),
            new ProductOrder (12, 19),
            new ProductOrder (12, 13),
            new ProductOrder (12, 11),
            new ProductOrder (12, 6),
            new ProductOrder (13, 11),
            new ProductOrder (13, 24),
            new ProductOrder (13, 26),
            new ProductOrder (13, 23),
            new ProductOrder (14, 18),
            new ProductOrder (15, 16),
            new ProductOrder (15, 13),
            new ProductOrder (15, 7),
            new ProductOrder (16, 23),
            new ProductOrder (16, 29),
            new ProductOrder (16, 18),
            new ProductOrder (16, 16),
            new ProductOrder (16, 22),
            new ProductOrder (16, 26),
            new ProductOrder (17, 18),
            new ProductOrder (17, 4),
            new ProductOrder (18, 13),
            new ProductOrder (18, 3),
            new ProductOrder (18, 27),
            new ProductOrder (18, 2),
            new ProductOrder (19, 26),
            new ProductOrder (19, 22),
            new ProductOrder (19, 18),
            new ProductOrder (19, 14),
            new ProductOrder (19, 15),
            new ProductOrder (19, 13),
            new ProductOrder (20, 22),
            new ProductOrder (21, 21),
            new ProductOrder (21, 26),
            new ProductOrder (22, 7),
            new ProductOrder (22, 6),
            new ProductOrder (23, 27),
            new ProductOrder (23, 7),
            new ProductOrder (23, 11),
            new ProductOrder (23, 5),
            new ProductOrder (24, 24),
            new ProductOrder (24, 2),
            new ProductOrder (24, 6),
            new ProductOrder (24, 28),
            new ProductOrder (24, 4),
            new ProductOrder (25, 28),
            new ProductOrder (25, 17),
            new ProductOrder (25, 2),
            new ProductOrder (25, 29),
            new ProductOrder (25, 19),
            new ProductOrder (26, 4),
            new ProductOrder (27, 6),
            new ProductOrder (27, 15),
            new ProductOrder (27, 24),
            new ProductOrder (28, 22),
            new ProductOrder (28, 9),
            new ProductOrder (29, 22),
            new ProductOrder (30, 29),
            new ProductOrder (30, 6),
            new ProductOrder (30, 8),
            new ProductOrder (31, 16),
            new ProductOrder (31, 12),
            new ProductOrder (31, 28),
            new ProductOrder (32, 8),
            new ProductOrder (32, 5),
            new ProductOrder (33, 12),
            new ProductOrder (33, 26),
            new ProductOrder (33, 21),
            new ProductOrder (33, 23),
            new ProductOrder (33, 29),
            new ProductOrder (33, 13),
            new ProductOrder (34, 1),
            new ProductOrder (34, 6),
            new ProductOrder (34, 22),
            new ProductOrder (34, 19),
            new ProductOrder (34, 13),
            new ProductOrder (34, 27),
            new ProductOrder (35, 5),
            new ProductOrder (35, 11),
            new ProductOrder (35, 26),
            new ProductOrder (35, 9),
            new ProductOrder (36, 28),
            new ProductOrder (36, 7),
            new ProductOrder (37, 15),
            new ProductOrder (37, 11),
            new ProductOrder (38, 18),
            new ProductOrder (38, 11),
            new ProductOrder (38, 14),
            new ProductOrder (38, 20),
            new ProductOrder (38, 7),
            new ProductOrder (39, 1),
            new ProductOrder (39, 21),
            new ProductOrder (40, 12),
            new ProductOrder (40, 10),
            new ProductOrder (40, 11),
            new ProductOrder (40, 29),
            new ProductOrder (40, 1),
            new ProductOrder (41, 13),
            new ProductOrder (41, 19),
            new ProductOrder (41, 5),
            new ProductOrder (41, 29),
            new ProductOrder (41, 14),
            new ProductOrder (41, 4),
            new ProductOrder (42, 2),
            new ProductOrder (43, 6),
            new ProductOrder (44, 20),
            new ProductOrder (44, 18),
            new ProductOrder (44, 8),
            new ProductOrder (44, 24),
            new ProductOrder (44, 26),
            new ProductOrder (44, 13),
            new ProductOrder (45, 23),
            new ProductOrder (45, 1),
            new ProductOrder (45, 25),
            new ProductOrder (45, 15),
            new ProductOrder (46, 16),
            new ProductOrder (46, 24),
            new ProductOrder (46, 19),
            new ProductOrder (46, 13),
            new ProductOrder (46, 11),
            new ProductOrder (47, 23),
            new ProductOrder (47, 28),
            new ProductOrder (47, 20),
            new ProductOrder (47, 21),
            new ProductOrder (48, 15),
            new ProductOrder (48, 3),
            new ProductOrder (48, 26),
            new ProductOrder (48, 7),
            new ProductOrder (48, 19),
            new ProductOrder (48, 10),
            new ProductOrder (49, 5),
            new ProductOrder (49, 13),
            new ProductOrder (49, 29),
            new ProductOrder (49, 3),
            new ProductOrder (49, 12),
            new ProductOrder (49, 17),
            new ProductOrder (50, 15),
            new ProductOrder (50, 16)
        );
    }
}